/* Conversas do fliperama.
   Cada personagem tem uma HISTÓRIA (lore) que vai sendo contada aos poucos — no máximo 2 partes por dia, a primeira no
   primeiro encontro — e uma lista de CURIOSIDADES (coisas que se aprende por volta dos 9 anos), ditas do jeito de cada um.
   Entre as partes da história entram as curiosidades, sem repetir até acabar a lista.
   '|' quebra a fala em páginas. {nome} vira o nome do piloto ({NOME} em maiúsculas, para o robô).
   req:['id',n] = essa parte só aparece depois que o outro personagem contou n partes da história dele. */
const CONVERSAS={
kai:{nome:'KAI',
  historia:[
    {t:'Oi! Eu sou o Kai. Minha mãe é engenheira aqui da estação. Enquanto ela conserta os motores, eu jogo hóquei!'},
    {t:'Sabia que eu nasci na Terra, em Porto Alegre? Faz dois anos que a gente mora aqui na estação.'},
    {t:'O Zorp é de outro planeta e, no começo, eu tinha um pouco de medo dele.|Agora ele é meu parceiro de hóquei. E o melhor goleiro da estação!'},
    {t:'Minha mãe disse que, se eu me esforçar na escola, posso visitar a sala dos motores. Estou treinando a tabuada todo dia.'},
    {t:'Ontem o Zorp ganhou de 7 a 5. Descobri o truque dele: ele mexe as antenas para me distrair!'},
    {t:'Sabe do que eu mais sinto falta da Terra? Da chuva. Aqui na estação nunca chove.',req:['tito',2]},
    {t:'Fui na sala dos motores! Minha mãe me mostrou o reator. Parecia um solzinho preso numa garrafa.'},
    {t:'Quando eu crescer, quero ser piloto igual a você, {nome}. Um dia você me ensina a pilotar?'}],
  fatos:[
    'Sabia que o coração de uma criança bate umas 90 vezes por minuto? Quando eu jogo, ele acelera para levar mais oxigênio para os músculos.',
    'Se eu faço 3 pontos por partida e jogo 4 partidas, são 3 × 4 = 12 pontos. A tabuada serve até para placar!',
    'O corpo humano adulto tem 206 ossos. O menor fica dentro do ouvido e se chama estribo.',
    'Mais da metade do nosso corpo é água. Por isso eu sempre levo a garrafinha para o hóquei.',
    'Um minuto tem 60 segundos e uma hora tem 60 minutos. Então uma hora tem 60 × 60 = 3.600 segundos!',
    'Quando eu bato no disco, ele vai para a frente e o taco empurra a minha mão para trás.|Minha mãe disse que isso é ação e reação, uma das leis de Newton.',
    'Dividir é repartir igual: 12 discos para 3 jogadores dá 4 para cada um. Porque 3 × 4 = 12!',
    'A gente tem cinco sentidos: visão, audição, olfato, paladar e tato. No hóquei eu uso quase todos. Paladar não, né?',
    'Os músculos trabalham em dupla: quando um puxa o braço, o outro estica. Por isso é bom alongar antes de jogar.',
    'Número par divide por 2 sem sobrar nada. 8 é par. 7 é ímpar: sempre sobra 1.',
    'Dormir bem ajuda o cérebro a guardar o que a gente aprendeu no dia. É por isso que minha mãe me manda deitar cedo!',
    'Metade é 1/2. Se a partida dura 10 minutos, na metade do jogo já passaram 5.']},
zorp:{nome:'ZORP',
  historia:[
    {t:'Zorp! Eu sou o Zorp, do planeta Glimmer. Lá o céu é verde e a gente tem três luas.'},
    {t:'Na minha língua, "oi" se diz "blimp-blimp". Estou aprendendo português com o Kai e o Tito. Falo bem?'},
    {t:'No começo o Kai fugia de mim. Acho que foram as antenas.|Agora a gente joga hóquei todo dia. Eu ganho quase sempre. Quase!'},
    {t:'Hoje provei um tal de pão de queijo, feito pelo pai do Tito. Vocês da Terra comem coisas maravilhosas!'},
    {t:'Sinto saudade da minha avó. Ela tem 300 anos glimmerianos e conta histórias das estrelas antes de dormir.'},
    {t:'O R-0B tenta a garra faz dias. Acho que ele quer pegar o bichinho para dar de presente a alguém...'},
    {t:'Mandei uma mensagem para casa. Glimmer é tão longe que até a luz demora muito para chegar lá.'},
    {t:'A Luna me deu um mapa com as constelações que dá para ver daqui. Agora eu sei para que lado fica a minha casa.',req:['luna',6]},
    {t:'{nome}, se um dia você for a Glimmer, minha família faz uma festa com gosma de cometa. É uma delícia, juro!'}],
  fatos:[
    'A Terra é o único planeta conhecido com oceanos de água líquida. Eles cobrem quase três quartos dela! No Glimmer, os mares são de gelatina.',
    'Nas escolas do Brasil se aprende que a Terra tem seis continentes: América, Europa, África, Ásia, Oceania e a gelada Antártida.',
    'A Floresta Amazônica é a maior floresta tropical do mundo, e a maior parte dela fica no Brasil. Tem mais tipos de árvore do que eu consigo contar com as antenas!',
    'As plantas fazem a própria comida com luz do sol, água e ar. Isso se chama fotossíntese. Eu queria almoçar só tomando sol!',
    'A baleia-azul é o maior animal que já viveu na Terra. Ela é maior que um ônibus! E come bichinhos minúsculos chamados krill.',
    'Vocês têm o esqueleto por dentro. Os insetos têm uma casca dura por fora, chamada exoesqueleto. Eu tenho os dois. Brincadeira!',
    'O Brasil tem 26 estados e o Distrito Federal, onde fica Brasília, a capital.',
    'O rio Amazonas carrega mais água que qualquer outro rio do mundo. Em alguns lugares, não dá nem para ver a outra margem!',
    'A Lua não tem luz própria: ela brilha porque reflete a luz do Sol. As três luas do Glimmer fazem igualzinho.',
    'Um dia na Terra tem 24 horas: é o tempo de uma volta dela em torno de si mesma. No Glimmer o dia tem 40 horas. Dá um sono!',
    'Os camaleões mudam de cor para se esconder ou mostrar o humor. Eu tentei, mas só fico mais verde.',
    'As abelhas levam pólen de flor em flor e assim as plantas conseguem fazer frutos. Sem abelhas, teria pouca maçã e pouco morango!']},
rob:{nome:'R-0B',robo:true,
  historia:[
    {t:'SAUDAÇÕES. SOU R-0B, ROBÔ DE MANUTENÇÃO DA ESTAÇÃO. NO MEU TEMPO LIVRE, TENTO A GARRA.'},
    {t:'ESTA É A TENTATIVA XLVII. EM NÚMEROS NORMAIS: 47. RESULTADO: NADA AINDA.'},
    {t:'OBJETIVO: O ALIENZINHO ROXO DE PELÚCIA. É PARA A LUNA. ELA GOSTA DE TUDO QUE VEM DO ESPAÇO.'},
    {t:'CONSULTA: O QUE É "AMIZADE"? MEU MANUAL TEM 4.096 PÁGINAS E NENHUMA FALA DISSO.'},
    {t:'O KAI DISSE QUE AMIZADE É GOSTAR DE ESTAR PERTO DE ALGUÉM.|ENTÃO TENHO 4 AMIGOS. 5 COM VOCÊ, {NOME}.'},
    {t:'ALERTA: A GARRA SOLTOU O ALIENZINHO NO ÚLTIMO SEGUNDO. SENSAÇÃO ESTRANHA NOS CIRCUITOS. O TITO DISSE QUE SE CHAMA "FRUSTRAÇÃO".'},
    {t:'APRENDI QUE ERRAR FAZ PARTE. CADA TENTATIVA ME MOSTRA ONDE MIRAR MELHOR. PROBABILIDADE DE SUCESSO: SUBINDO.'},
    {t:'CONSEGUI! O ALIENZINHO ROXO! JÁ ENTREGUEI PARA A LUNA.|MEUS CIRCUITOS ESTÃO... QUENTINHOS. ACHO QUE ISSO É "ALEGRIA".'}],
  fatos:[
    'NÚMEROS ROMANOS: I = 1, V = 5, X = 10, L = 50, C = 100. QUANDO O MENOR VEM ANTES DO MAIOR, SUBTRAI: IV = 4, IX = 9.',
    'DICA PARA HUMANOS: 5, 6, 7, 8 → 56 = 7 × 8. OS NÚMEROS APARECEM EM ORDEM!',
    'TABUADA DO 9: SOME OS ALGARISMOS DO RESULTADO E DÁ 9. 9 × 3 = 27, E 2 + 7 = 9. FUNCIONA ATÉ 9 × 10 = 90.',
    'MULTIPLICAR POR 10 É FÁCIL: COLOQUE UM ZERO NO FIM. 23 × 10 = 230.',
    'DIVISÃO COM RESTO: 17 ÷ 5 = 3, E SOBRAM 2. VERIFICAÇÃO: 5 × 3 = 15, E 15 + 2 = 17.',
    'MEU CÉREBRO USA SÓ DOIS NÚMEROS: 0 E 1. DESLIGADO E LIGADO. ISSO SE CHAMA SISTEMA BINÁRIO.',
    'ANO MMXXVI = 2026. MM = 2.000, XX = 20, VI = 6. SOMANDO: 2.026.',
    'UM QUILÔMETRO TEM 1.000 METROS. UM METRO TEM 100 CENTÍMETROS. MEU BRAÇO MEDE 60 CENTÍMETROS.',
    'FRAÇÃO: UMA PIZZA EM 8 PEDAÇOS. COMENDO 3, VOCÊ COMEU 3/8. ROBÔS NÃO COMEM PIZZA. SÓ CALCULAM.',
    'NÚMERO PRIMO SÓ DIVIDE POR 1 E POR ELE MESMO: 2, 3, 5, 7, 11, 13... MEU FAVORITO É O 7.',
    'NA SOMA A ORDEM NÃO IMPORTA: 3 + 10 = 10 + 3. NA SUBTRAÇÃO IMPORTA: 10 − 3 = 7.',
    'QUADRADO: 4 LADOS IGUAIS. TRIÂNGULO: 3 LADOS. HEXÁGONO: 6 LADOS, COMO AS CASINHAS DOS FAVOS DE MEL.',
    'PERÍMETRO É A VOLTA TODA DA FIGURA. UM QUADRADO DE LADO 5 TEM PERÍMETRO 5 + 5 + 5 + 5 = 20.']},
luna:{nome:'LUNA',
  historia:[
    {t:'Oi! Eu sou a Luna. Meu nome vem da Lua, e eu quero ser astrônoma quando crescer.'},
    {t:'Tenho um caderno onde anoto as estrelas que vejo pela janela da estação. Já são 132!'},
    {t:'Meu pai trabalha no observatório lá em cima. Às vezes ele me deixa olhar no telescópio grande.'},
    {t:'O R-0B fica o dia inteiro na garra. Será que ele quer algum bichinho em especial?'},
    {t:'Ontem passou um cometa pela janela! A cauda dele aponta sempre para o lado contrário do Sol.'},
    {t:'Estou desenhando um mapa das constelações para dar ao Zorp. Ele sente saudade de casa.'},
    {t:'O R-0B me deu um alienzinho roxo de pelúcia! Dei o nome de Plutinho.',req:['rob',8]},
    {t:'{nome}, quando você pilotar por aí, me conta o que viu? Vou anotar no meu caderno, com o seu nome.'}],
  fatos:[
    'O Sol é uma estrela! Ele parece maior que as outras só porque está muito mais perto da gente.',
    'Os planetas, a partir do Sol: Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano e Netuno.',
    'Júpiter é o maior planeta do Sistema Solar. Caberiam mais de mil Terras dentro dele!',
    'A Lua leva mais ou menos um mês para dar a volta na Terra. Por isso as fases mudam: nova, crescente, cheia e minguante.',
    'Os anéis de Saturno são feitos de pedaços de gelo e rocha. Tem pedaço pequeno como grão de areia e pedaço do tamanho de uma casa!',
    'A luz do Sol leva uns 8 minutos para chegar à Terra. Quando você olha o Sol, está vendo como ele era 8 minutos atrás!',
    'Marte é o planeta vermelho por causa da ferrugem que cobre o chão dele.',
    'Do Brasil dá para ver o Cruzeiro do Sul, uma constelação que aponta para o sul. Ela aparece até na bandeira!',
    'Na Lua não tem vento nem chuva. Por isso as pegadas dos astronautas que foram lá em 1969 continuam no chão!',
    'Plutão já foi chamado de planeta, mas desde 2006 é um planeta-anão. Ele é menor que a nossa Lua!',
    'A Terra leva um ano, uns 365 dias, para dar uma volta completa em torno do Sol.',
    'Estrela cadente não é estrela: é uma pedrinha do espaço que pega fogo quando entra no ar da Terra.',
    'Vênus é o planeta mais quente, mesmo não sendo o mais perto do Sol. As nuvens grossas dele prendem o calor.']},
tito:{nome:'TITO',
  historia:[
    {t:'Bah, e aí! Sou o Tito. Meu pai é o cozinheiro da estação. É ele que faz o pão de queijo que o Zorp adora.'},
    {t:'A gente veio do Rio Grande do Sul. Meu pai trouxe a cuia de chimarrão até para o espaço!'},
    {t:'Estou ensinando o Zorp a falar "bah" e "tchê". Ele já fala melhor que eu!'},
    {t:'Meu pai está fazendo uma horta aqui na estação, sem terra: só água, adubo e luz. Isso se chama hidroponia.'},
    {t:'Nasceram os primeiros tomates da horta! Pequenininhos, mas o pai ficou todo faceiro.'},
    {t:'O Kai sente falta da chuva. Eu sinto falta do cheiro de churrasco no domingo.',req:['kai',6]},
    {t:'Vamos fazer um almoço para a turma do fliperama, com salada da horta. Até o R-0B vai, só para conversar.'},
    {t:'{nome}, tu é convidado de honra do almoço, tchê! Traz o teu apetite.'}],
  fatos:[
    'A água pode ser líquida, gelo ou vapor. O sol esquenta o mar, a água vira vapor, forma nuvem e cai como chuva. É o ciclo da água!',
    'Frutas e verduras têm vitaminas que ajudam o corpo a crescer forte. Meu pai diz que prato colorido é prato saudável.',
    'A capivara é o maior roedor do mundo e vive no Brasil, sempre perto de rios e lagoas.',
    'O chimarrão é feito com erva-mate, uma planta da América do Sul. Os povos guaranis já tomavam muito antes da gente.',
    'Porto Alegre é a capital do Rio Grande do Sul e fica na beira do Guaíba.',
    'Planta precisa de luz, água e ar para crescer. Na horta da estação, a luz vem de lâmpadas especiais!',
    'Arroz com feijão é uma dupla e tanto: o arroz dá energia e o feijão tem ferro, que ajuda o sangue.',
    'Dentro de uma semente tem uma plantinha bebê e um lanche guardado para ela começar a crescer.',
    'Casca de fruta e resto de verdura podem virar adubo para a horta. Isso se chama compostagem.',
    'Receita é cheia de frações: meia xícara é 1/2 e um quarto de xícara é 1/4. Duas metades fazem uma xícara inteira!',
    'O pinhão é a semente da araucária, uma árvore típica do Sul do Brasil. Cozido no inverno, fica uma delícia!',
    'Lavar as mãos com sabão tira os micróbios que a gente nem consegue ver. Meu pai lava umas cem vezes por dia na cozinha.']},
nino:{nome:'SEU NINO',
  historia:[
    {t:'Olá, jovem piloto! Sou o Seu Nino. Antes de cuidar dos prêmios, dirigi caminhão espacial por 30 anos.'},
    {t:'Cada bichinho desta prateleira veio de um lugar que visitei. O azul é de Netuno, o amarelo é de Vênus.'},
    {t:'As crianças daqui são minha turma. A Luna me pergunta das estrelas e o Tito me traz pão de queijo quentinho.'},
    {t:'Uma vez fiquei três dias parado numa tempestade de poeira em Marte. Passei o tempo contando histórias para mim mesmo.'},
    {t:'O R-0B veio pedir dicas da garra. Falei para ele: paciência e mira, como numa boa estrada.'},
    {t:'Guardo embaixo do balcão uma foto minha bem jovem, com o meu primeiro caminhão. Era vermelho igualzinho ao sofá!'},
    {t:'Sabe por que gosto daqui? Ver vocês rindo me lembra da minha neta, que mora na Terra.'},
    {t:'{nome}, você tem jeito de explorador. Continue estudando: o universo é cheio de perguntas esperando resposta.'}],
  fatos:[
    'Em 1500 os portugueses chegaram ao Brasil com Pedro Álvares Cabral. Mas muitos povos indígenas já viviam aqui havia milhares de anos.',
    'O Brasil ficou independente de Portugal em 1822. Dizem que o grito foi às margens do riacho Ipiranga, em São Paulo.',
    'O Brasil é o maior país da América do Sul. Ele faz fronteira com quase todos os países do continente, menos o Chile e o Equador.',
    'Falamos português por causa dos portugueses, mas muitas palavras vieram das línguas indígenas, como abacaxi, pipoca e capivara.',
    'Os pontos cardeais são norte, sul, leste e oeste. O Sol nasce do lado leste e se põe do lado oeste.',
    'Brasília virou a capital do Brasil em 1960. Antes, a capital era o Rio de Janeiro.',
    'Um acentinho muda tudo: "avó" é a vovó e "avô" é o vovô.',
    'Os dinossauros viveram milhões de anos antes das pessoas. No Rio Grande do Sul acharam alguns dos dinossauros mais antigos do mundo!',
    'Uma década tem 10 anos, um século tem 100 e um milênio tem 1.000 anos.',
    'O oceano que banha o Brasil é o Atlântico. Do outro lado dele fica a África.',
    'A bandeira do Brasil tem 27 estrelas: uma para cada estado e uma para o Distrito Federal.',
    'Antes dos mapas no celular, os viajantes se guiavam pelas estrelas. Eu ainda acho o sul pelo Cruzeiro do Sul!']}
};
